version: '3.4'

services:
  stableDeffusiondb:
    container_name: stableDeffusiondb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
        
  stabledeffusion.api:
    container_name: stabledeffusion.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:MongoDb=mongodb://stableDeffusiondb:27017
    depends_on:
      - stableDeffusiondb
    ports:
      - "5286:8080"
        
        
  react-app:
    container_name: react-app
    ports:
      - "3000:3000"  # Доступ к React с хоста
    volumes:
      - ./client-app:/app  # Hot-reload для разработки
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://stabledeffusion.api:8080
      - REACT_APP_WS_URL=ws://stabledeffusion.api:8080