version: '3.4'

services:
  stableDeffusiondb:
    image: mongo


  stabledeffusion.api:
    image: ${DOCKER_REGISTRY-}stabledeffusionapi
    build:
      context: .
      dockerfile: SDService/Dockerfile
      
      
  react-app:
    build:
      context: ./client-app
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    depends_on:
      - stabledeffusion.api

volumes:
  mongo_data: