version: '3.4'

services:
  stableDeffusiondb:
    image: mongo


  stabledeffusion.api:
    image: ${DOCKER_REGISTRY-}stabledeffusionapi
    build:
      context: .
      dockerfile: SDService/Dockerfile

volumes:
  mongo_data: