version: '3.4'

services:
  stableDeffusiondb:
    container_name: stableDeffusiondb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
        
  stabledeffusion.api:
    container_name: stabledeffusion.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:MongoDb=mongodb://stableDeffusiondb:27017
    depends_on:
      - stableDeffusiondb
    ports:
      - "5286:8080"
    restart: always